### ISSUE TITLE
Folder sharing should happen before Composer install

### ISSUE THREAD

**Issue by zupolgec** [rocketeers/rocketeer#331]
I started using Rocketeer 2 with Laravel 5 and I noticed a problem: now sharing folders takes place _after_ dependencies install. This is a problem because sharing files also shares the ".env" file that is required by Laravel Artisan (that is triggered after Composer install).

How can I change the task sequence?

**Comment by pvdbroek** [comment]
@zupolgec How did you install Rocketeer on Laravel 5? I'm getting a in-compatibility error when I try to install with coomposer:
...
 - anahkiasen/rocketeer 2.1.2 requires illuminate/log ~4.2
...

**Comment by zupolgec** [comment]
@pvdbroek I switched to Deployer

**Comment by pvdbroek** [comment]
@zupolgec thanks for your response. I hope I can keep using rocketeer as I already set it up while using Laravel 4...

**Comment by Anahkiasen** [comment]
Rocketeer is not planned to be compatible as an in-project dependency with Laravel 5, it was just too limitating in terms of what it allowed Rocketeer to do because I was stuck with the dependencies Laravel picked and that blocked features I wanted to ship. Rocketeer is framework agnostic, I couldn't just remove features because of Laravel.

You can still use Rocketeer with a L5 app simply by installing globally with the PHAR or Composer.

**Comment by pvdbroek** [comment]
Thanks @Anahkiasen , both for your answer and your great piece of software!
