### ISSUE TITLE
SVN checkout fails because of duplicated credentials

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#337]
Using version 2.0.1, running `rocketeer deploy --verbose`:

```
...
|-- Primer (Run local checks to ensure deploy can proceed)
|-- CreateRelease (Creates a new release on the server) [~0.2s]
|---- Deploy/Clone (Clones a fresh instance of the repository by SCM)
|===> Cloning repository in "/data/www/myapp/releases/20141027114737"
$ svn co https://foo:bar@example.com/svn/myapp/trunk /data/www/myapp/releases/20141027114737 --non-interactive --username="foo" --password="bar"
[user@example.com] (production) svn: E170000: 'https://foo:bar@example.com/svn/myapp/trunk' isn't in the same repository as 'https://foo:XXXXXXXX@example.com/svn/myapp/trunk'
```

When testing manually, it is fixed when I remove the credentials from the url:

`svn co https://example.com/svn/myapp/trunk /data/www/myapp/releases/20141027114737 --non-interactive --username="foo" --password="bar"`

**Comment by infoeon** [comment]
This problem is happening again in 2.2.3

**Comment by infoeon** [comment]
It appears that the issue is that the regex statement in rocketeer/src/Rocketeer/Binaries/Vcs/Svn.php:91 assumes an alphanumeric password. Some passwords contain symbols such as ! @ # $ etc and may be URL encoded.  There are existing PHP methods that parse URLs (mainly parse_url) that should be used instead of hacking together a regex.
