### ISSUE TITLE
Enhancement: determine if Rocketeer should ask key/password

### ISSUE THREAD

**Issue by marcovtwout** [rocketeers/rocketeer#407]
When I have neither password or key filled out in my connection config, Rocketeer prompts:

`No password or SSH key is set for [staging/0], which would you use? (key) [key/password]`

Rocketeer could skip the question and ask for password directly, if I set my config like this:

```
'connections'      => array(
		'staging' => array(
			...
			'password'  => '',
			'key' => false,
```

**Comment by Anahkiasen** [comment]
This is actually already possible on develop but it's not quite working fully yet, need to squish a few bugs

**Comment by Anahkiasen** [comment]
Will continue tracking in #190

**Comment by marcovtwout** [comment]
Are you sure this issue is fixed with #190?

**Comment by Anahkiasen** [comment]
Hm it should be yes, is it not working?

**Comment by marcovtwout** [comment]
Nope, I am prompted with the same question as above. My config:

```
'staging' => array(
			'host'      => 'xxxxxxxxx.com',
			'username'  => '`xxxxx',
			'password'  => '',
			'key'       => false,
			'keyphrase' => '',
			'agent'     => false,
			'db_role'   => true,
		),
```

**Comment by marcovtwout** [comment]
Could you please reopen this ticket?

**Comment by Anahkiasen** [comment]
R3 will not prompt the user anymore besides during ignition. All this code to compute whether to ask for X or Y was needlessly complicated and hindered the user more than it helped so I trashed it. 

You'll now ignite your application and Rocketeer will prompt you _once_ (asking you more questions than before tho) and then responsibility is moved to the user, since the main benefit of repeated prompts was not needing to track credentials in the repo and that's now handled by having a .env file
