### ISSUE TITLE
Direct Download Link won't work

### ISSUE THREAD

**Issue by aftabnaveed** [rocketeers/rocketeer#445]
I tried this 
wget http://rocketeer.autopergamene.eu/versions/rocketeer.phar

and it would take me to 

http://rocketeer.autopergamene.eu/versions/rocketeer.phar#/docs/rocketeer/README

**Comment by Anahkiasen** [comment]
Yup sorry, migrating some things on the server, PHAR will be back shortly

**Comment by aftabnaveed** [comment]
is it production ready? I see some of the fixes in develop not yet ported to master, It still has this issue
https://github.com/rocketeers/rocketeer/issues/410

and current master version is 
<code>
php rocketeer --version
Rocketeer version 2.0.4
</code>

**Comment by Anahkiasen** [comment]
Not sure I get your question, do you mean Rocketeer is usable for work? It is yes, has been for quite a while, I use it personally, I'm just in between a server migration currently. #410 is closed as far as I know, latest stable is indeed 2.0.4

**Comment by Anahkiasen** [comment]
Ok no I just got what you meant. There will be a 2.0.5 soon, I just need to manually backport some fixes, since the next release (on the `develop` branch) is 3.0-dev it contains some major changes in the codebase and I can't just merge back develop to master, tag and call it a day, but the fix in #410 will be included in it yes

**Comment by aftabnaveed** [comment]
Yes I was testing and see if I can use it for production, I do see the #410 is closed, but it worked for @thasmo  on version 2.1.0 not 2.0.4,  and current master has 2.0.4, I am assuming master has the latest stable release.

**Comment by Anahkiasen** [comment]
2.1.0 was the project previous tag that became 3.0.0 that's why you can't currently find it, you can track the progress of 2.0.5 in #438

**Comment by aftabnaveed** [comment]
so you think I shall use 3.0.0 for production, and  are there any known bugs I shall be aware of ?

**Comment by aftabnaveed** [comment]
@Anahkiasen sorry I am a bit lost here, I don't see any tag for version 3.0.x in tags,  the latest tag I see is 2.0.4 which apparently has aforementioned bug, can you please point me in the right direction here?

**Comment by Anahkiasen** [comment]
2.0.4 is the latest stable release (`master` branch), that is the one that is publicly available and that you will get when you download the PHAR (which should be available again now).
3.0.0 is the name of future release (`develop` branch), it's not yet an actual tag because it's not released yet, it's still a work in progress. As Rocketeer follows semver this will be a major version (ie. no BC) so I don't recommend using it yet if you're unsure about what you're doing as the docs won't be updated for it until a closer point to the release

**Comment by Anahkiasen** [comment]
2.0.4 is good for production, I use it every day. There are some bugs that were done for 3.0 but were not backported yet but this doesn't mean you'll encounter them. If you have any issue you can always come ping me on the Gitter chat (check the README), I check it fairly often so you can ask me any question or tell me if you encounter any bug.

**Comment by aftabnaveed** [comment]
thank you I am now able to download the PHAR for 2.0.4 which apparently is missing Boris\Boris,  I think 
<code>PHP Fatal error:  Class 'Boris\Boris' not found in phar:///usr/local/bin/rocketeer/src/Rocketeer/Console/Commands/TinkerCommand.php on line 26</code>
to stick with composer version which has all the dependencies,    

I think to create a new issues since the download is now working, but I am not sure if the Boris\Boris missing component is some thing I am missing or something caused during compilation of PHAR archive.

**Comment by Anahkiasen** [comment]
Yes that's one of the bugfixes I need to backport to 2.0.4, it only happens when using the PHAR. There are a few other ways to use Rocketeer so you could use them in the meantime, I recommend the [global composer install](http://rocketeer.autopergamene.eu/#/docs/docs/I-Introduction/Getting-started) way

**Comment by Anahkiasen** [comment]
Will backport this fix right now and regenerate the PHAR on the server so that at least this one is out of the way.

**Comment by aftabnaveed** [comment]
thank you much appreciated.

**Comment by Anahkiasen** [comment]
Pushed the fix and rebuild the master PHAR, should work now:

```
Macedoine ➜  Sites  wget http://rocketeer.autopergamene.eu/versions/rocketeer-master.phar
Macedoine ➜  Sites  php rocketeer-master.phar tinker
[1] rocketeer> class_exists('Boris\Boris');
```

Be careful to get `rocketeer-master.phar` not `rocketeer.phar` – the former points to the latest commit on the master branch, the latter is just an alias for the latest tag (2.0.4)

**Comment by aftabnaveed** [comment]
thanks mate, but that won't actually resolve my issue #410, I am digging into the code myself now, or may be try the develop branch :-)
