### ISSUE TITLE
Forge preset

### ISSUE THREAD

**Issue by barryvdh** [rocketeers/rocketeer#597]
Seeing that Rocketeer is popular with Laravel, it might be interesting to create a Forge profile or something. Not sure how to best handle this, but these are the changes/steps to use on Forge:

 - Default username is forge, authentication is key (path should be set, key asked?)
 - Default application name is 'default' (or app_directory)
 - root_directory = /home/forge
 - app_directory = default
 - shared: storage + .env
 - writable: storage
 - chown: could be `chown -R forge:www-data %s`?

Next to that, forge uses a default /public folder in the app dir and assumes `.env` in the app dir also.
This could be manually linked (current/public -> public, .env -> shared/.env), but perhaps this could be an option to make it easier?

Perhaps a `rocketeer ignite --forge`  or something could be created, that sets these defaults and asks better questions, targeted to forge. And a custom strategy to add the symlinks.

What do you think?

**Comment by Anahkiasen** [comment]
This could be doable in 3.0 as configuration is generated by `symfony/config` from a provided PHP array yes

**Comment by Anahkiasen** [comment]
Not going to implement this in the end, I feel it is too opinionated to be part of Rocketeer. If it was part of the Laravel plugin yes but the issue is Rocketeer doesn't know which plugins the user will end up using before ignition (since those are configured in the config). I could load all plugins by default but I'm afraid it would cause issues if you deploy different apps of different types and have plugins that bump into each other. 

If the benefit was greater I would try to find a way but in this case at best you'd shave a few seconds changing two/three options as a lot of those are asked during ignition in R3 now (root path, etc)
