### ISSUE TITLE
Custom tasks - I'm a bit lost ...

### ISSUE THREAD

**Issue by GesJeremie** [rocketeers/rocketeer#611]
Hi guys :) 

I know it's difficult to maintain and make a good documentation (I have a project myself), but seriously i'm just lost in this documentation ...

In short, I installed globally the package (saw an issue on that thread about local install with laravel 5). I setup everything and I deployed on my remote server, that's a good start. 

I saw by default rocketeer try to npm install, bower install, etc ... I tried to find a way to rip that, but impossible to find an helpful information :(

I tried to migrate my database with ``$ rocketeer deploy --migrate``, but the artisan command can't run because my app is in "production mode", if you know what I mean.

My deployment process is quiet simple, I want to:

- Update composer 
- Copy/Paste the right .env file (Laravel 5)
- Go to a folder "front" and run "bower install && npm install && brunch b --production"
- Migrate the database with "artisan migrate" without the problem said upside
- Get a shit load of money and have sex with some girls 

How I can setup everything for that ?

Kind regards,
Jérémie from space.

**Comment by pelletiermaxime** [comment]
I recently moved to http://deployer.org/ because of how much simpler it is to config and how it works out of the box, but I can still try to help you.

> I saw by default rocketeer try to npm install, bower install, etc ... I tried to find a way to rip that, but impossible to find an helpful information :(

The default strategy for dependencies is Polyglot. See http://rocketeer.autopergamene.eu/#/docs/docs/II-Concepts/Strategies or try "rocketeer strategies" to see a description of the different dependencies strategies.


> Update composer
> Go to a folder "front" and run "bower install && npm install && brunch b --production"
> Migrate the database with "artisan migrate" without the problem said upside

What I would do is use the 'Composer' dependencies strategy and then add those tasks in the before-symlink hooks. Something like this:

```php
'before-symlink'  => [
        'deploy'  => [
            'bower install',
            'npm install',
            'brunch -b --production',
            'sudo service php5-fpm reload',
            function ($task) {
                 $task->artisan()->runForCurrentRelease('cache:clear');
                 $task->artisan()->runForCurrentRelease('config:clear');
                 $task->artisan()->runForCurrentRelease('route:clear');
                 $task->artisan()->runForCurrentRelease('migrate --force');
            },
        ],
    ],
```

> Copy/Paste the right .env file (Laravel 5)

Add '.env' to the 'shared' config in remote.php and then create the .env file in the shared directory on the server.

**Comment by GesJeremie** [comment]
Thanks for your time man ;)
