### ISSUE TITLE
Use "--xml" flag, when querying Subversion

### ISSUE THREAD

**Issue by aik099** [rocketeers/rocketeer#637]
Right now the https://github.com/rocketeers/rocketeer/blob/master/src/Rocketeer/Scm/Svn.php file parsing text output from SVN commands. This would only work on server with English locale.

To make it work any server the XML output of each command (e.g. `svn info --xml`) needs to parsed instead.

**Comment by Anahkiasen** [comment]
I'm not familiar with SVN, how would you parse the result of that command?

**Comment by aik099** [comment]
The `svn info` result:

```
Path: .
URL: svn://alex@in-portal.org/in-portal/branches/5.2.x
Repository Root: svn://alex@in-portal.org
Repository UUID: 2d19b2cd-e369-0410-8045-b8fb98e743af
Revision: 16347
Node Kind: directory
Schedule: normal
Last Changed Author: alex
Last Changed Rev: 16347
Last Changed Date: 2016-04-02 17:39:49 +0300 (Sat, 02 Apr 2016)
```

The `svn info --xml` result:

```xml
<?xml version="1.0"?>
<info>
<entry
   kind="dir"
   path="."
   revision="16347">
<url>svn://alex@in-portal.org/in-portal/branches/5.2.x</url>
<repository>
<root>svn://alex@in-portal.org</root>
<uuid>2d19b2cd-e369-0410-8045-b8fb98e743af</uuid>
</repository>
<wc-info>
<schedule>normal</schedule>
<depth>infinity</depth>
</wc-info>
<commit
   revision="16347">
<author>alex</author>
<date>2016-04-02T14:39:49.607970Z</date>
</commit>
</entry>
</info>
```

As you can see the same (even more) data is shown, but no locale strings involved.

I've did a lot of such stuff parsing myself, while creating https://github.com/console-helpers/svn-buddy project. I've used http://php.net/manual/en/function.simplexml-load-string.php function.

**Comment by Anahkiasen** [comment]
Ended up using `svn info --show-item`, that seemed to work as far as I can see:

```bash
$ svn info --show-item revision
1780560
$ svn info --show-item url
http://svn.apache.org/repos/asf/spamassassin/trunk
```

That being said I'm not an SVN guy, can you confirm this is correct?

**Comment by aik099** [comment]
Are you sure, that `--show-item` is option of `svn info` command, that is available in every SVN client version? I wasn't able to find any docs about it. Maybe it's SVN 1.9 addition.

The docs for SVN 1.6, 1.7 and 1.8 doesn't mention this option: http://svnbook.red-bean.com/en/1.6/svn.ref.svn.c.info.html.

**Comment by Anahkiasen** [comment]
Rah goddammit I knew it couldn't be that simple :D The issue is I tried the XML way but since the VCS classes do not actually execute anything right away (they merely tell Rocketeer what to run) I have to use regexes to get infos from the XML from the command line.

Now for the URL that's fine, my issue is with the revision since there are two revisions returned by `--xml`, each on their own line, so I'm not sure how to properly sed the right one nor what each of them correspond to. 

Note that it's not that the VCS classes _cannot_ under any circumstances execute things, it's just that it brings better consistency when they don't (per example in case you run with --pretend, stuff like that). So worst case we could just, actually get the XML, parse it in PHP and call it a day.

Do you have an idea how this could be handled otherwise?

**Comment by aik099** [comment]
> Rah goddammit I knew it couldn't be that simple :D The issue is I tried the XML way but since the VCS classes do not actually execute anything right away (they merely tell Rocketeer what to run) I have to use regexes to get infos from the XML from the command line.

Are you sure they don't? If we look at commit you've made: https://github.com/rocketeers/rocketeer/commit/2d03df25b46933413bd1767f24b8700614169bfa then both `currentState` and `currentEndpoint` called `getCommand` method. I guess `getCommand` already executes command. That already invalidates what you said about `not executing stuff`.

**Comment by aik099** [comment]
In the `getInformationAttribute` method you've added you can do `simplexml_load_string` on command result and just get needed property from it.
